spring:
  application:
    name: backend
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 60000
      lettuce:
        pool:
          max-active: 8 #nhận 8 kết nối
          max-idle: 8 #8 kết nối chờ sẵn
          min-idle: 0 #số lượng kết nối tối thiểu luôn duy trì trong pool

  datasource:
    url: jdbc:mysql://localhost:3306/NT118
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "15a54f9abdccf354b2afcd1008f8b6e8f78640a4ce4d38a5d01b7d25806dc4ed"
server:
  port: 8080
  servlet:
    context-path: /NT118


