spring:
  application:
    name: backend
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 60000
      lettuce:
        pool:
          max-active: 8 #nhận 8 kết nối
          max-idle: 8 #8 kết nối chờ sẵn
          min-idle: 0 #số lượng kết nối tối thiểu luôn duy trì trong pool

  datasource:
    url: jdbc:mysql://localhost:3306/NT118
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  sigerKey: "5f7aa140ecd9f3a9ad700c6b6ef2549395b9dc68eee93c5d64789a2b217c7706"
server:
  port: 8080
  servlet:
    context-path: /NT118


